### ISSUE TITLE
IndexError: pop from empty list when using "neg_rmse"

### ISSUE THREAD

**Issue by outdoteth** [brendenpetersen/deep-symbolic-optimization#23]
My program:

```python
from dso import DeepSymbolicRegressor
import pandas as pd

df = pd.read_csv("/path/to/file/ml_data.csv")

inputs = df[["1", "2"]].values[0:100]
labels = df[["y"]].values[:, 0][0:100]

# Create the model
model = DeepSymbolicRegressor({
    "task": {
      "task_type" : "regression",      
      "function_set": ["add", "sub", "mul", "div", "sin", "cos", "exp", "log"],      
      "metric" : "neg_rmse",     # <- when changing this to "inv_nrmse" it works
      "metric_params" : [],      
      "extra_metric_test" : None,      
      "extra_metric_test_params" : [],      
      "threshold" : 1e-12,      
      "protected" : False,      
      "reward_noise" : 0.0,      
      "reward_noise_type" : "r",      
      "normalize_variance" : False,      
      "decision_tree_threshold_set" : []
    }
}) 

# Fit the model
model.fit(inputs, labels)  # Should solve in ~10 seconds

```

After 1 epoch of training, this is the error that is outputted. If I switch the metric to "inv_nrmse" then the error doesn't happen and the model trains just fine. Am I configuring something incorrectly?

```
Traceback (most recent call last):
  File "dsr.py", line 35, in <module>
    model.fit(inputs, labels)  # Should solve in ~10 seconds
  File "/dso/dso/task/regression/sklearn.py", line 33, in fit
    train_result = self.train()
  File "/deep-symbolic-optimization/dso/dso/core.py", line 83, in train
    **self.config_training))
  File "/deep-symbolic-optimization/dso/dso/train.py", line 263, in learn
    deap_programs, deap_actions, deap_obs, deap_priors = gp_controller(actions)
  File "deep-symbolic-optimization/dso/dso/gp/gp_controller.py", line 221, in __call__
    nevals = self.algorithm(self.hof, i) # Run one generation
  File "/deep-symbolic-optimization/dso/dso/gp/base.py", line 159, in __call__
    population, invalid_ind, uncached_ind = self._eval(offspring)
  File "deep-symbolic-optimization/dso/dso/gp/base.py", line 100, in _eval
    p = programs.pop(0)
IndexError: pop from empty list

```

**Comment by brendenpetersen** [comment]
Hi, thanks for pointing this out! You were configuring everything correctly; it looks like there was a bug when using GP with reward metrics that allow `-np.inf`. (We typically stick to `inv_nrmse` as the `[0, 1]` range makes training more stable.) I pushed a hotfix--could you please check that this works? I can't exactly reproduce your error because I don't have your dataset, but hopefully I fixed the logic error. Thanks!

**Comment by outdoteth** [comment]
Yep that did the trick 👍🏼  thanks.
