### ISSUE TITLE
Error running PiecewiseFunction-1.json example, of Failed to import malformed source string: state_checker

### ISSUE THREAD

**Issue by samholt** [brendenpetersen/deep-symbolic-optimization#30]
Hi Brendon and Team,

Love the project, however running the `PiecewiseFunction-1.json` throws an error of the following:

```
python -m dso.run ./config/examples/regression/PiecewiseFunction-1.json

== EXPERIMENT SETUP START ===========
Task type            : regression
Dataset              : task/regression/data/PiecewiseFunction-1.csv
Starting seed        : 0
Runs                 : 1
== EXPERIMENT SETUP END =============

== TRAINING SEED 0 START ============
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/sd2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sam/anaconda3/envs/sd2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sam/code/discovery/sd2/dso/dso/run.py", line 156, in <module>
    main()
  File "/home/sam/anaconda3/envs/sd2/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/anaconda3/envs/sd2/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sam/anaconda3/envs/sd2/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/anaconda3/envs/sd2/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/code/discovery/sd2/dso/dso/run.py", line 139, in main
    result, summary_path = train_dso(config)
  File "/home/sam/code/discovery/sd2/dso/dso/run.py", line 33, in train_dso
    result = model.train()
  File "/home/sam/code/discovery/sd2/dso/dso/core.py", line 74, in train
    self.setup()
  File "/home/sam/code/discovery/sd2/dso/dso/core.py", line 67, in setup
    self.prior = self.make_prior()
  File "/home/sam/code/discovery/sd2/dso/dso/core.py", line 140, in make_prior
    prior = make_prior(Program.library, self.config_prior)
  File "/home/sam/code/discovery/sd2/dso/dso/prior.py", line 43, in make_prior
    prior_class = import_custom_source(prior_type)
  File "/home/sam/code/discovery/sd2/dso/dso/utils.py", line 214, in import_custom_source
    assert m is not None and m.end() == len(import_source), "*** Failed to import malformed source string: "+import_source
AssertionError: *** Failed to import malformed source string: state_checker
```

Could you let me know what I can do to fix this, or point me in the right direction, it seems it is trying to find a custom prior called state checker, that cannot be found and error's, I could be incorrect here.

Thank you so much, really excited to use DSO for our current research applied projects,

OS: Ubuntu 20.04 LTS “Focal Fossa,”

Output of pip freeze is:

```
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1637088766493/work
astor @ file:///home/conda/feedstock_root/build_artifacts/astor_1593610464257/work
atari-py==0.2.9
attrs==21.4.0
box2d-py==2.3.8
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi==2021.10.8
click==8.0.4
cloudpickle==1.2.2
commentjson==0.9.0
cycler==0.11.0
Cython==0.29.28
deap==1.3.1
dill==0.3.4
-e git+ssh://git@github.com/samholt/sd2.git@62f845d625e260d03efeefd5f9ddf7c3ec6a1c41#egg=dso&subdirectory=dso
fonttools==4.31.2
future==0.18.2
gast @ file:///home/conda/feedstock_root/build_artifacts/gast_1636964356021/work
google-pasta==0.2.0
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1624380491840/work
gym==0.15.4
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1624405626125/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1647210388949/work
iniconfig==1.1.1
joblib==1.1.0
Keras-Applications==1.0.8
Keras-Preprocessing @ file:///home/conda/feedstock_root/build_artifacts/keras-preprocessing_1610713559828/work
kiwisolver==1.4.0
lark-parser==0.7.8
llvmlite==0.36.0
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1637220118004/work
matplotlib==3.5.1
mpi4py==3.1.3
mpmath==1.2.1
multiprocess==0.70.12.2
numba==0.53.1
numpy==1.19.0
opencv-python==4.5.5.64
packaging==21.3
pandas==1.3.5
pathos==0.2.8
Pillow==9.0.1
pluggy==1.0.0
pox==0.3.0
ppft==1.6.6.4
progress==1.6
protobuf==3.17.2
py==1.11.0
pybullet==3.2.1
pyglet==1.3.2
pyparsing==3.0.7
pytest==7.1.1
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
scikit-learn==1.0.2
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1626684342480/work
seaborn==0.11.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
stable-baselines==2.10.0
sympy==1.10.1
tensorboard==1.14.0
tensorflow @ file:///home/conda/feedstock_root/build_artifacts/tensorflow_1594833314895/work/tensorflow_pkg/tensorflow-1.14.0-cp37-cp37m-linux_x86_64.whl
tensorflow-estimator==1.14.0
termcolor==1.1.0
threadpoolctl==3.1.0
tomli==2.0.1
tqdm==4.63.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1644850595256/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1644332431572/work
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1610094880759/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1643828507773/work
```

Any help is very much appreciated, thank you,

All the best,
Sam

**Comment by brendenpetersen** [comment]
Hi Sam,

The `StateChecker` token (and the prior it's referencing) is currently not supported/included in this release. We should have removed that `PiecewiseFunction-1.json` example. We have a separate internal version of the repo and it's been a challenge to properly maintain both.

That said, `StateChecker` will be available in an incoming updating in the future :)

Thanks,
Brenden

**Comment by samholt** [comment]
> Hi Sam,
> 
> The `StateChecker` token (and the prior it's referencing) is currently not supported/included in this release. We should have removed that `PiecewiseFunction-1.json` example. We have a separate internal version of the repo and it's been a challenge to properly maintain both.
> 
> That said, `StateChecker` will be available in an incoming updating in the future :)
> 
> Thanks, Brenden

Hi Brenden,

I love your code base and I am using it to inspire new similar methods, for different cases of SR, and wish to cite your work,(s) and use it as a benchmark. As such do you have any date expected for the new release ? No worries just wondering if it will be within the next 3 weeks or so. No worries if not. Open to a zoom call anytime to discuss what I am working on, if I can help your work at all. 

Thank you for your time,

All the best,
Sam

**Comment by brendenpetersen** [comment]
Shoot me an email :) It can be found in one of the paper PDFs.
